In [293]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [294]:
data = pd.read_csv('fake_bills(1).csv')

In [295]:
data

is_genuine;diagonal;height_left;height_right;margin_low;margin_up;length
0            True;171.81;104.86;104.95;4.52;2.89;112.83                      
1            True;171.46;103.36;103.66;3.77;2.99;113.09                      
2              True;172.69;104.48;103.5;4.4;2.94;113.16                      
3            True;171.36;103.91;103.94;3.62;3.01;113.51                      
4            True;171.73;104.28;103.46;4.04;3.48;112.54                      
...                                                 ...                      
1495        False;171.75;104.38;104.17;4.42;3.09;111.28                      
1496        False;172.19;104.63;104.44;5.27;3.37;110.97                      
1497         False;171.8;104.01;104.12;5.51;3.36;111.95                      
1498        False;172.06;104.28;104.06;5.17;3.46;112.25                      
1499        False;171.47;104.15;103.82;4.63;3.37;112.07                      

[1500 rows x 1 columns]

In [296]:
# first we gotta clean teh data


In [297]:
data.values

array([['True;171.81;104.86;104.95;4.52;2.89;112.83'],
       ['True;171.46;103.36;103.66;3.77;2.99;113.09'],
       ['True;172.69;104.48;103.5;4.4;2.94;113.16'],
       ...,
       ['False;171.8;104.01;104.12;5.51;3.36;111.95'],
       ['False;172.06;104.28;104.06;5.17;3.46;112.25'],
       ['False;171.47;104.15;103.82;4.63;3.37;112.07']], dtype=object)

In [298]:
rows = []

for i in range(data.shape[0]):
    rows.append(data.loc[i].str.split(';').values)

In [299]:
rows

[array([list(['True', '171.81', '104.86', '104.95', '4.52', '2.89', '112.83'])],
       dtype=object),
 array([list(['True', '171.46', '103.36', '103.66', '3.77', '2.99', '113.09'])],
       dtype=object),
 array([list(['True', '172.69', '104.48', '103.5', '4.4', '2.94', '113.16'])],
       dtype=object),
 array([list(['True', '171.36', '103.91', '103.94', '3.62', '3.01', '113.51'])],
       dtype=object),
 array([list(['True', '171.73', '104.28', '103.46', '4.04', '3.48', '112.54'])],
       dtype=object),
 array([list(['True', '172.17', '103.74', '104.08', '4.42', '2.95', '112.81'])],
       dtype=object),
 array([list(['True', '172.34', '104.18', '103.85', '4.58', '3.26', '112.81'])],
       dtype=object),
 array([list(['True', '171.88', '103.76', '104.08', '3.98', '2.92', '113.08'])],
       dtype=object),
 array([list(['True', '172.47', '103.92', '103.67', '4.0', '3.25', '112.85'])],
       dtype=object),
 array([list(['True', '172.47', '104.07', '104.02', '4.04', '3.25', '113.45'

In [300]:
cols = data.columns.str.split(';')
cols

Index([['is_genuine', 'diagonal', 'height_left', 'height_right', 'margin_low', 'margin_up', 'length']], dtype='object')

In [301]:
def colInfo(n):
    info = []
    for i in range(len(rows)):
        info.append(rows[i][0][n])
    return info


In [302]:
col1 = colInfo(0)
col2 = colInfo(1)

col3 = colInfo(2)
col4 = colInfo(3)
col5 = colInfo(4)
col6 = colInfo(5)
col7 = colInfo(6)


In [303]:
data =  pd.DataFrame({ "is_genuine":col1,
              "diagonal": col2,
              "height_left":col3,
              "height_right": col4,
              "margin_low":col5,
              "margin_up":col6,
              "length":col7
})

In [304]:
data

is_genuine diagonal height_left height_right margin_low margin_up  length
0          True   171.81      104.86       104.95       4.52      2.89  112.83
1          True   171.46      103.36       103.66       3.77      2.99  113.09
2          True   172.69      104.48        103.5        4.4      2.94  113.16
3          True   171.36      103.91       103.94       3.62      3.01  113.51
4          True   171.73      104.28       103.46       4.04      3.48  112.54
...         ...      ...         ...          ...        ...       ...     ...
1495      False   171.75      104.38       104.17       4.42      3.09  111.28
1496      False   172.19      104.63       104.44       5.27      3.37  110.97
1497      False    171.8      104.01       104.12       5.51      3.36  111.95
1498      False   172.06      104.28       104.06       5.17      3.46  112.25
1499      False   171.47      104.15       103.82       4.63      3.37  112.07

[1500 rows x 7 columns]

# True = 0 and False =1

In [305]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   is_genuine    1500 non-null   object
 1   diagonal      1500 non-null   object
 2   height_left   1500 non-null   object
 3   height_right  1500 non-null   object
 4   margin_low    1500 non-null   object
 5   margin_up     1500 non-null   object
 6   length        1500 non-null   object
dtypes: object(7)
memory usage: 82.2+ KB


In [306]:
def convert(n):
    """Converts a number to a string and then to a list of characters."""
    n = str(n)
    if n =='True':
        return 0.0
    else:
        return 1.0

In [307]:
data['is_genuine']=data['is_genuine'].apply(convert)

In [308]:
data['is_genuine'].describe

<bound method NDFrame.describe of 0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
1495    1.0
1496    1.0
1497    1.0
1498    1.0
1499    1.0
Name: is_genuine, Length: 1500, dtype: float64>

In [309]:
from sklearn.model_selection import train_test_split


In [310]:
data['is_genuine']

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
1495    1.0
1496    1.0
1497    1.0
1498    1.0
1499    1.0
Name: is_genuine, Length: 1500, dtype: float64

In [311]:
data["diagonal"] = pd.to_numeric(data["diagonal"])
data["height_left"] = pd.to_numeric(data["height_left"])
data["height_right"] = pd.to_numeric(data["height_right"])
data["margin_low"] = pd.to_numeric(data["margin_low"])
data["margin_up"] = pd.to_numeric(data["margin_up"])
data["length"] = pd.to_numeric(data["length"])


In [312]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   is_genuine    1500 non-null   float64
 1   diagonal      1500 non-null   float64
 2   height_left   1500 non-null   float64
 3   height_right  1500 non-null   float64
 4   margin_low    1463 non-null   float64
 5   margin_up     1500 non-null   float64
 6   length        1500 non-null   float64
dtypes: float64(7)
memory usage: 82.2 KB


In [313]:
data['margin_low'] = data['margin_low'].fillna(value=data['margin_low'].mean())

In [314]:
data['margin_low'].isna().sum()

0

In [315]:

y = data['is_genuine']
data = data.drop('is_genuine',axis =1)
x = data

In [316]:
x

diagonal  height_left  height_right  margin_low  margin_up  length
0       171.81       104.86        104.95        4.52       2.89  112.83
1       171.46       103.36        103.66        3.77       2.99  113.09
2       172.69       104.48        103.50        4.40       2.94  113.16
3       171.36       103.91        103.94        3.62       3.01  113.51
4       171.73       104.28        103.46        4.04       3.48  112.54
...        ...          ...           ...         ...        ...     ...
1495    171.75       104.38        104.17        4.42       3.09  111.28
1496    172.19       104.63        104.44        5.27       3.37  110.97
1497    171.80       104.01        104.12        5.51       3.36  111.95
1498    172.06       104.28        104.06        5.17       3.46  112.25
1499    171.47       104.15        103.82        4.63       3.37  112.07

[1500 rows x 6 columns]

In [317]:
y

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
1495    1.0
1496    1.0
1497    1.0
1498    1.0
1499    1.0
Name: is_genuine, Length: 1500, dtype: float64

In [318]:
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=101)

In [319]:
x_train

diagonal  height_left  height_right  margin_low  margin_up  length
729     171.04       103.84        103.64        4.22       3.36  112.70
510     171.87       103.87        104.27        4.44       2.94  112.95
100     171.53       104.02        103.87        4.10       3.03  113.32
1054    172.39       104.16        103.92        5.66       3.39  111.83
1055    171.74       104.07        104.08        5.06       3.52  111.76
...        ...          ...           ...         ...        ...     ...
1417    171.21       103.92        104.29        5.18       3.12  111.70
75      172.26       103.85        103.70        4.16       3.20  112.35
599     172.31       103.93        103.32        4.73       2.85  113.23
1361    171.95       104.47        104.34        5.92       3.10  113.17
863     171.97       104.00        103.37        3.86       3.21  112.87

[1050 rows x 6 columns]

In [320]:
y_train

729     0.0
510     0.0
100     0.0
1054    1.0
1055    1.0
       ... 
1417    1.0
75      0.0
599     0.0
1361    1.0
863     0.0
Name: is_genuine, Length: 1050, dtype: float64

In [321]:
from sklearn.neighbors import KNeighborsClassifier

In [322]:
knn = KNeighborsClassifier(n_neighbors=1)

In [323]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [324]:
pred = knn.predict(x_test)

In [325]:
pred

array([1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0.

In [326]:
y_test

1051    1.0
1285    1.0
1271    1.0
778     0.0
1235    1.0
       ... 
790     0.0
412     0.0
1039    1.0
1293    1.0
485     0.0
Name: is_genuine, Length: 450, dtype: float64

In [327]:
from sklearn.metrics import classification_report, confusion_matrix

In [328]:
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[304   1]
 [  5 140]]
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99       305
         1.0       0.99      0.97      0.98       145

    accuracy                           0.99       450
   macro avg       0.99      0.98      0.98       450
weighted avg       0.99      0.99      0.99       450



In [329]:
# if we increase the neighbors
knn = KNeighborsClassifier(n_neighbors=15)


In [330]:
knn.fit(x_train, y_train)
pred = knn.predict(x_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[305   0]
 [  4 141]]
              precision    recall  f1-score   support

         0.0       0.99      1.00      0.99       305
         1.0       1.00      0.97      0.99       145

    accuracy                           0.99       450
   macro avg       0.99      0.99      0.99       450
weighted avg       0.99      0.99      0.99       450



hence we get a better accuracy on our model